# Generated by Django 5.2.1 on 2025-06-01 17:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Дайте название файла')),
                ('text', models.TextField(max_length=200, verbose_name='Заполните описанием')),
                ('file', models.FileField(help_text="Файлы должны быть в форматах ['docx', 'doc', 'xml', 'xslx', 'pdf']", upload_to='forms/', validators=[django.core.validators.FileExtensionValidator(['docx', 'doc', 'xml', 'xslx', 'pdf'], "Файл должен быть с расширением ['docx', 'doc', 'xml', 'xslx', 'pdf']")], verbose_name='Загрузите файл')),
            ],
            options={
                'verbose_name': 'Бланк заказа',
                'verbose_name_plural': 'Бланки заказов',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now=True, verbose_name='Дата')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
