# Generated by Django 5.2.1 on 2025-06-02 08:12

import django.db.models.deletion
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Введите название категории')),
                ('img', models.ImageField(upload_to='category/img', verbose_name='Выберите изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название модели', max_length=20, verbose_name='Внесите заголовок')),
                ('description', models.TextField(help_text='Описание', verbose_name='Напишите описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='product/img', verbose_name='Фото товара')),
                ('file', models.FileField(help_text="Модель в 3Д в форматах ['.stl', '.glb'] ", upload_to='product/models', validators=[products.validators.file_validator], verbose_name='Выберите 3Д модель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
